import path from "node:path"
import fs from "node:fs"
import {
  app,
  BrowserWindow,
  globalShortcut,
  session,
  shell,
  type Extension,
  type Session,
} from "electron"
import { createLogger } from "../core/logger"

/**
 * Chrome 扩展（MV3）测试宿主。
 *
 * 注意：这里加载的是「真正的 Chrome 扩展」（chrome-plugin/demo-plugin/manifest.json，
 * manifest_version: 3），走 Electron 原生 `session.loadExtension`，
 * 与 features/extension/ 那套自研插件宿主（digital-employee.extension.json）完全无关。
 *
 * Electron 对 Chrome 扩展的支持是「尽力而为」：
 *  - ✅ 后台 service worker（background/index.js）会运行
 *  - ✅ content scripts（content/recorder.js）会按 matches 自动注入页面
 *  - ✅ chrome.storage / chrome.tabs / chrome.scripting / chrome.webNavigation 等基础 API
 *  - ⚠️ 不渲染工具栏图标，所以 popup 需要我们自己开一个窗来测（见 openExtensionPopupWindow）
 *  - ⚠️ chrome.tabCapture / chrome.offscreen 等高级 API 不保证可用，需实测
 */

const log = createLogger("chrome-ext-tester")

/** 独立 partition，避免污染主应用 session */
const TEST_PARTITION = "persist:chrome-ext-demo"

/** 默认测试用真实网页（content script 会注入到这里） */
const DEFAULT_TEST_URL = "https://example.com"

let loadedExtension: Extension | null = null

function getDemoExtensionDir(): string {
  // APP_ROOT 在 dev 与打包态均指向 apps/web（见 core/app-context.ts createAppPaths）
  const appRoot = process.env.APP_ROOT ?? path.join(app.getAppPath())
  return path.join(appRoot, "electron", "chrome-plugin", "demo-plugin")
}

/**
 * Electron 兼容垫片：在后台 SW(background/index.js)求值之前注入。
 *
 * 这版插件在 Electron 里有两个崩点：
 *  1. 后台顶层就调用 `chrome.webNavigation.onCompleted.addListener`，而 Electron 不实现
 *     `chrome.webNavigation` → SW 一加载就 TypeError → onMessage 没注册上 → popup「没反应」。
 *  2. 录制时 `chrome.tabCapture.getMediaStreamId` 同样缺失 → START_RECORDING 崩。
 *
 * 垫片把缺失 API 桩掉，并拦截发往 offscreen 的录制消息（假装成功），
 * 让「步骤/JSON 采集」整条链路跑通；视频部分留空（用户已确认本期不做视频）。
 */
const ELECTRON_SHIM_SOURCE = `// AUTO-GENERATED by chrome-ext-tester. Do not edit; regenerated each launch.
;(() => {
  const c = globalThis.chrome
  if (!c) return
  const setProp = (obj, key, value) => {
    try { obj[key] = value; if (obj[key] === value) return true } catch (_) {}
    try { Object.defineProperty(obj, key, { value, writable: true, configurable: true }); return true } catch (_) {}
    return false
  }
  const event = () => ({ addListener() {}, removeListener() {}, hasListener() { return false } })

  // 1) webNavigation：后台顶层 onCompleted.addListener 必须先存在；getAllFrames 返回空 → 回退到顶层 frame
  if (!c.webNavigation) {
    setProp(c, "webNavigation", {
      onCompleted: event(), onCommitted: event(), onDOMContentLoaded: event(),
      getAllFrames: async () => [],
    })
  }

  // 2) tabCapture：返回假 streamId，让录制流不崩（视频另由 offscreen 拦截绕过）
  if (!c.tabCapture) {
    setProp(c, "tabCapture", {
      getMediaStreamId: (_opts, cb) => {
        const id = "electron-shim-no-video"
        if (typeof cb === "function") { cb(id); return }
        return Promise.resolve(id)
      },
    })
  }

  // 3) tabs.captureVisibleTab：逐步截图，桩成 undefined（调用处有 try/catch）
  if (c.tabs && !c.tabs.captureVisibleTab) {
    setProp(c.tabs, "captureVisibleTab", async () => undefined)
  }

  // 3.5) tabs.query：Electron 里 popup 是独立窗口，{active,currentWindow} 可能命中
  // popup 自己的 chrome-extension:// 页，导致后台 ut() 报「内置页面无法注入」。
  // 回退：拿不到真实网页时，从所有 tab 里挑一个 http(s) 页。
  if (c.tabs && typeof c.tabs.query === "function") {
    const realQuery = c.tabs.query.bind(c.tabs)
    const isWeb = (t) => !!(t && t.url && /^https?:\\/\\//.test(t.url))
    setProp(c.tabs, "query", (info, cb) => {
      const run = async () => {
        const res = await realQuery(info)
        if (info && info.active && !res.some(isWeb)) {
          const web = (await realQuery({})).filter(isWeb)
          if (web.length) return [web[web.length - 1]]
        }
        return res
      }
      if (typeof cb === "function") { run().then(cb); return }
      return run()
    })
  }

  // 4) 拦截发往 offscreen 的录制消息，假装成功，绕过基于 tabCapture 的 getUserMedia
  if (c.runtime && typeof c.runtime.sendMessage === "function") {
    const real = c.runtime.sendMessage.bind(c.runtime)
    setProp(c.runtime, "sendMessage", (...args) => {
      const msg = args[0]
      const type = msg && typeof msg === "object" ? msg.type : undefined
      if (type === "OFFSCREEN_START" || type === "OFFSCREEN_RELEASE") {
        return Promise.resolve({ ok: true, payload: {} })
      }
      if (type === "OFFSCREEN_STOP") {
        return Promise.resolve({ ok: true, payload: { objectUrl: "", mimeType: "video/webm", sizeBytes: 0 } })
      }
      return real(...args)
    })
  }

  // 5) offscreen.createDocument 改 no-op，避免真去申请 USER_MEDIA
  if (c.offscreen) {
    setProp(c.offscreen, "hasDocument", async () => false)
    setProp(c.offscreen, "createDocument", async () => {})
    setProp(c.offscreen, "closeDocument", async () => {})
  }

  console.log("[electron-shim] applied: webNavigation/tabCapture stubbed, offscreen recording bypassed")
})()
`

const SHIM_IMPORT_LINE = 'import"./electron-shim.js";'

/**
 * 把 demo-plugin 拷到可写目录并打补丁，返回打过补丁的扩展目录。
 * 源码保持干净；每次启动重拷重打，跟随源码重新构建。
 */
function preparePatchedExtensionDir(): string {
  const src = getDemoExtensionDir()
  const dst = path.join(app.getPath("userData"), "chrome-ext-demo-patched")

  fs.rmSync(dst, { recursive: true, force: true })
  fs.cpSync(src, dst, { recursive: true })

  const shimPath = path.join(dst, "background", "electron-shim.js")
  fs.writeFileSync(shimPath, ELECTRON_SHIM_SOURCE, "utf8")

  const idxPath = path.join(dst, "background", "index.js")
  let code = fs.readFileSync(idxPath, "utf8")
  if (!code.startsWith(SHIM_IMPORT_LINE)) {
    code = SHIM_IMPORT_LINE + code
    fs.writeFileSync(idxPath, code, "utf8")
  }

  log.info("patched extension prepared", { dst })
  return dst
}

function getTestSession(): Session {
  return session.fromPartition(TEST_PARTITION)
}

/**
 * 加载 demo 扩展到测试 session。重复调用直接返回已加载实例。
 */
export async function loadDemoExtension(): Promise<Extension> {
  if (loadedExtension) return loadedExtension

  if (!fs.existsSync(path.join(getDemoExtensionDir(), "manifest.json"))) {
    throw new Error(
      `[chrome-ext-tester] 找不到 manifest.json：${getDemoExtensionDir()}`
    )
  }
  // 加载打过 Electron 兼容补丁的副本，而非源目录
  const dir = preparePatchedExtensionDir()

  const sess = getTestSession()
  // allowFileAccess: 允许扩展在 file:// 页面注入/访问，方便本地页面测试
  const ext = await sess.loadExtension(dir, { allowFileAccess: true })
  loadedExtension = ext

  log.info("demo extension loaded", {
    id: ext.id,
    name: ext.name,
    version: ext.version,
    dir,
  })

  // 捕获后台 service worker 的 console，便于排查
  sess.serviceWorkers.on("console-message", (_e, details) => {
    log.info("[ext sw]", {
      level: details.level,
      message: details.message,
      source: details.sourceUrl,
    })
  })

  return ext
}

/**
 * 打开一个真实网页窗口（使用测试 session），content script 会自动注入。
 * 默认开 DevTools，方便观察 recorder.js 的日志与录制行为。
 */
export async function openChromeExtTestWindow(
  url: string = process.env.CHROME_EXT_URL || DEFAULT_TEST_URL,
): Promise<BrowserWindow> {
  await loadDemoExtension()

  const win = new BrowserWindow({
    width: 1100,
    height: 800,
    title: "Chrome 扩展测试页",
    webPreferences: {
      partition: TEST_PARTITION,
      contextIsolation: true,
      nodeIntegration: false,
    },
  })

  // 外链交给系统浏览器，避免测试窗被导航走
  win.webContents.setWindowOpenHandler(({ url: openUrl }) => {
    void shell.openExternal(openUrl)
    return { action: "deny" }
  })

  await win.loadURL(url)
  win.webContents.openDevTools({ mode: "right" })

  log.info("test window opened", { url })
  return win
}

/**
 * 打开扩展的 popup.html。
 *
 * Electron 不渲染浏览器工具栏图标，所以「点扩展图标弹出的 popup」无法原生触发，
 * 这里直接用 chrome-extension://<id>/popup.html 把 popup 当成普通页面开出来测。
 * popup 内的 chrome.tabs.query({active:true}) 会命中测试 session 里最近聚焦的标签页，
 * 所以建议先 openChromeExtTestWindow 再开 popup。
 */
export async function openExtensionPopupWindow(): Promise<BrowserWindow> {
  const ext = await loadDemoExtension()

  const popupWin = new BrowserWindow({
    width: 380,
    height: 560,
    title: `${ext.name} · popup`,
    resizable: true,
    webPreferences: {
      partition: TEST_PARTITION,
      contextIsolation: true,
      nodeIntegration: false,
    },
  })

  const popupUrl = `chrome-extension://${ext.id}/popup.html`
  await popupWin.loadURL(popupUrl)
  popupWin.webContents.openDevTools({ mode: "detach" })

  log.info("popup window opened", { popupUrl })
  return popupWin
}

/**
 * 一键启动测试：加载扩展 + 开测试页 + 开 popup。
 * 供 main 在 dev 下（CHROME_EXT_DEMO=1）调用。
 */
export async function startChromeExtDemo(): Promise<void> {
  try {
    await loadDemoExtension()
    await openChromeExtTestWindow()
    await openExtensionPopupWindow()
    registerDemoShortcuts()
  } catch (err) {
    log.error("startChromeExtDemo failed", {
      message: err instanceof Error ? err.message : String(err),
    })
  }
}

/**
 * 全局快捷键，方便运行时随时重开测试窗口，免重启：
 *  - Ctrl/Cmd+Shift+E：开一个新的网页测试窗
 *  - Ctrl/Cmd+Shift+P：开一个新的 popup 窗
 */
function registerDemoShortcuts(): void {
  const accelTest = "CommandOrControl+Shift+E"
  const accelPopup = "CommandOrControl+Shift+P"

  globalShortcut.register(accelTest, () => {
    void openChromeExtTestWindow()
  })
  globalShortcut.register(accelPopup, () => {
    void openExtensionPopupWindow()
  })

  app.once("will-quit", () => {
    globalShortcut.unregister(accelTest)
    globalShortcut.unregister(accelPopup)
  })

  log.info("demo shortcuts registered", { accelTest, accelPopup })
}

/** 卸载扩展（测试结束时可选调用） */
export function unloadDemoExtension(): void {
  if (!loadedExtension) return
  getTestSession().removeExtension(loadedExtension.id)
  log.info("demo extension unloaded", { id: loadedExtension.id })
  loadedExtension = null
}
