import type { Conversation } from "@/types/chat"

export const CONVERSATIONS: Conversation[] = [
  {
    id: "conv-1",
    title: "请假流程咨询",
    contactId: "hr-manager",
    status: "unread",
    lastMessage: "好的，我会帮你处理这个问题。",
    lastMessageTime: new Date(Date.now() - 30 * 60 * 1000),
    lastMessageType: "text",
    unreadCount: 2,
    updatedAt: new Date(Date.now() - 30 * 60 * 1000),
  },
  {
    id: "conv-2",
    title: "重构方案评审",
    contactId: "group-tech",
    status: "running",
    lastMessage: "王大明: 我们需要重新评估这个方案",
    lastMessageTime: new Date(Date.now() - 2 * 60 * 60 * 1000),
    lastMessageType: "text",
    unreadCount: 0,
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: "conv-3",
    title: "首页改版评审",
    contactId: "product-designer",
    status: "idle",
    lastMessage: "设计稿已经发给你了，请查收",
    lastMessageTime: new Date(Date.now() - 24 * 60 * 60 * 1000),
    lastMessageType: "text",
    unreadCount: 1,
    updatedAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
  {
    id: "conv-4",
    title: "Q2 产品路线讨论",
    contactId: "group-product",
    status: "error",
    lastMessage: "陈小红: 新的产品方案已经通过了",
    lastMessageTime: new Date(Date.now() - 3 * 60 * 60 * 1000),
    lastMessageType: "text",
    unreadCount: 0,
    updatedAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
  },
  {
    id: "conv-5",
    title: "AISO 产品路线讨论",
    contactId: "group-product",
    status: "running",
    lastMessage: "陈小红: 你看看你干的是什么",
    lastMessageTime: new Date(Date.now() - 10 * 60 * 1000),
    lastMessageType: "text",
    unreadCount: 0,
    updatedAt: new Date(Date.now() - 10 * 60 * 1000),
  },
]
