const encoder = new TextEncoder()

export function createMockSSEStream(
  sseText: string,
  options?: { delay?: number; chunkDelay?: number }
): ReadableStream<Uint8Array> {
  const { delay = 30, chunkDelay = 60 } = options ?? {}
  const events = sseText
    .trim()
    .split(/\n\n+/)
    .filter((event) => event.trim())

  return new ReadableStream<Uint8Array>({
    async start(controller) {
      for (const event of events) {
        await new Promise((resolve) => setTimeout(resolve, chunkDelay))
        const payload = event.trim() + "\n\n"
        controller.enqueue(encoder.encode(payload))
        await new Promise((resolve) => setTimeout(resolve, delay))
      }

      controller.close()
    },
    cancel() {},
  })
}

export const SeeData = String.raw`
data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "", "response_metadata": {"model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-0bda-79e2-a86f-4e636d46c223", "tool_calls": [{"name": "write_file", "args": {}, "id": "call_638c881117244592bb49d8", "type": "tool_call"}], "tool_call_chunks": [{"name": "write_file", "args": "", "id": "call_638c881117244592bb49d8", "index": 0, "type": "tool_call_chunk"}], "invalid_tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 4, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:d09621ce-89ca-cd85-cb13-dc97b1731127", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:d09621ce-89ca-cd85-cb13-dc97b1731127", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "", "response_metadata": {"model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-0bda-79e2-a86f-4e636d46c223", "tool_calls": [{"name": "", "args": {}, "id": "", "type": "tool_call"}], "tool_call_chunks": [{"name": null, "args": "{\"file_path\":", "id": "", "index": 0, "type": "tool_call_chunk"}], "invalid_tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 4, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:d09621ce-89ca-cd85-cb13-dc97b1731127", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:d09621ce-89ca-cd85-cb13-dc97b1731127", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "", "response_metadata": {"model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-0bda-79e2-a86f-4e636d46c223", "invalid_tool_calls": [{"name": null, "args": " \"/a.txt\",", "id": "", "error": null, "type": "invalid_tool_call"}], "tool_call_chunks": [{"name": null, "args": " \"/a.txt\",", "id": "", "index": 0, "type": "tool_call_chunk"}], "tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 4, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:d09621ce-89ca-cd85-cb13-dc97b1731127", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:d09621ce-89ca-cd85-cb13-dc97b1731127", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "", "response_metadata": {"model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-0bda-79e2-a86f-4e636d46c223", "invalid_tool_calls": [{"name": null, "args": " \"content\": \"", "id": "", "error": null, "type": "invalid_tool_call"}], "tool_call_chunks": [{"name": null, "args": " \"content\": \"", "id": "", "index": 0, "type": "tool_call_chunk"}], "tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 4, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:d09621ce-89ca-cd85-cb13-dc97b1731127", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:d09621ce-89ca-cd85-cb13-dc97b1731127", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "", "response_metadata": {"model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-0bda-79e2-a86f-4e636d46c223", "invalid_tool_calls": [{"name": null, "args": "这是一些随机", "id": "", "error": null, "type": "invalid_tool_call"}], "tool_call_chunks": [{"name": null, "args": "这是一些随机", "id": "", "index": 0, "type": "tool_call_chunk"}], "tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 4, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:d09621ce-89ca-cd85-cb13-dc97b1731127", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:d09621ce-89ca-cd85-cb13-dc97b1731127", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "", "response_metadata": {"model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-0bda-79e2-a86f-4e636d46c223", "invalid_tool_calls": [{"name": null, "args": "的内容。\\n这是", "id": "", "error": null, "type": "invalid_tool_call"}], "tool_call_chunks": [{"name": null, "args": "的内容。\\n这是", "id": "", "index": 0, "type": "tool_call_chunk"}], "tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 4, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:d09621ce-89ca-cd85-cb13-dc97b1731127", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:d09621ce-89ca-cd85-cb13-dc97b1731127", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "", "response_metadata": {"model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-0bda-79e2-a86f-4e636d46c223", "invalid_tool_calls": [{"name": null, "args": "第二行。\\n", "id": "", "error": null, "type": "invalid_tool_call"}], "tool_call_chunks": [{"name": null, "args": "第二行。\\n", "id": "", "index": 0, "type": "tool_call_chunk"}], "tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 4, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:d09621ce-89ca-cd85-cb13-dc97b1731127", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:d09621ce-89ca-cd85-cb13-dc97b1731127", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "", "response_metadata": {"model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-0bda-79e2-a86f-4e636d46c223", "invalid_tool_calls": [{"name": null, "args": "这是第三行。", "id": "", "error": null, "type": "invalid_tool_call"}], "tool_call_chunks": [{"name": null, "args": "这是第三行。", "id": "", "index": 0, "type": "tool_call_chunk"}], "tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 4, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:d09621ce-89ca-cd85-cb13-dc97b1731127", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:d09621ce-89ca-cd85-cb13-dc97b1731127", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "", "response_metadata": {"model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-0bda-79e2-a86f-4e636d46c223", "invalid_tool_calls": [{"name": null, "args": "\"}", "id": "", "error": null, "type": "invalid_tool_call"}], "tool_call_chunks": [{"name": null, "args": "\"}", "id": "", "index": 0, "type": "tool_call_chunk"}], "tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 4, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:d09621ce-89ca-cd85-cb13-dc97b1731127", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:d09621ce-89ca-cd85-cb13-dc97b1731127", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "", "response_metadata": {"finish_reason": "tool_calls", "model_name": "qwen2.5-72b-instruct", "model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-0bda-79e2-a86f-4e636d46c223", "tool_calls": [], "invalid_tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 4, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:d09621ce-89ca-cd85-cb13-dc97b1731127", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:d09621ce-89ca-cd85-cb13-dc97b1731127", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "", "type": "AIMessageChunk", "id": "lc_run--019d23a2-0bda-79e2-a86f-4e636d46c223", "chunk_position": "last", "tool_calls": [], "invalid_tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 4, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:d09621ce-89ca-cd85-cb13-dc97b1731127", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:d09621ce-89ca-cd85-cb13-dc97b1731127", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "ToolMessage"], "kwargs": {"content": "Cannot write to /a.txt because it already exists. Read and then make an edit, or write to a new path.", "type": "tool", "name": "write_file", "id": "4d2efadb-947d-406c-b182-bf86dcde824f", "tool_call_id": "call_638c881117244592bb49d8", "status": "success"}}, {"ls_integration": "deepagents", "langgraph_step": 6, "langgraph_node": "tools", "langgraph_triggers": ["__pregel_push"], "langgraph_path": ["__pregel_push", 0, false], "langgraph_checkpoint_ns": "tools:793ce779-a2f9-f89b-9804-a12851916ac6"}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "", "response_metadata": {"model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-1ac6-7c91-b517-2cd0178353aa", "tool_calls": [{"name": "read_file", "args": {}, "id": "call_6c944c1c8d874ea299df44", "type": "tool_call"}], "tool_call_chunks": [{"name": "read_file", "args": "{\"file", "id": "call_6c944c1c8d874ea299df44", "index": 0, "type": "tool_call_chunk"}], "invalid_tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 7, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:f4698e08-f611-d52c-f8d4-7ddb61fa237c", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:f4698e08-f611-d52c-f8d4-7ddb61fa237c", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "", "response_metadata": {"model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-1ac6-7c91-b517-2cd0178353aa", "invalid_tool_calls": [{"name": null, "args": "_path\": \"/a", "id": "", "error": null, "type": "invalid_tool_call"}], "tool_call_chunks": [{"name": null, "args": "_path\": \"/a", "id": "", "index": 0, "type": "tool_call_chunk"}], "tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 7, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:f4698e08-f611-d52c-f8d4-7ddb61fa237c", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:f4698e08-f611-d52c-f8d4-7ddb61fa237c", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "", "response_metadata": {"model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-1ac6-7c91-b517-2cd0178353aa", "invalid_tool_calls": [{"name": null, "args": ".txt\"}", "id": "", "error": null, "type": "invalid_tool_call"}], "tool_call_chunks": [{"name": null, "args": ".txt\"}", "id": "", "index": 0, "type": "tool_call_chunk"}], "tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 7, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:f4698e08-f611-d52c-f8d4-7ddb61fa237c", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:f4698e08-f611-d52c-f8d4-7ddb61fa237c", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "", "response_metadata": {"model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-1ac6-7c91-b517-2cd0178353aa", "tool_calls": [{"name": "", "args": {}, "id": "", "type": "tool_call"}], "tool_call_chunks": [{"name": null, "args": null, "id": "", "index": 0, "type": "tool_call_chunk"}], "invalid_tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 7, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:f4698e08-f611-d52c-f8d4-7ddb61fa237c", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:f4698e08-f611-d52c-f8d4-7ddb61fa237c", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "", "response_metadata": {"finish_reason": "tool_calls", "model_name": "qwen2.5-72b-instruct", "model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-1ac6-7c91-b517-2cd0178353aa", "tool_calls": [], "invalid_tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 7, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:f4698e08-f611-d52c-f8d4-7ddb61fa237c", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:f4698e08-f611-d52c-f8d4-7ddb61fa237c", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "", "type": "AIMessageChunk", "id": "lc_run--019d23a2-1ac6-7c91-b517-2cd0178353aa", "chunk_position": "last", "tool_calls": [], "invalid_tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 7, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:f4698e08-f611-d52c-f8d4-7ddb61fa237c", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:f4698e08-f611-d52c-f8d4-7ddb61fa237c", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "ToolMessage"], "kwargs": {"content": "System reminder: File exists but has empty contents", "type": "tool", "name": "read_file", "id": "1a8a924c-3253-4c00-940d-e5c1474fb85a", "tool_call_id": "call_6c944c1c8d874ea299df44", "status": "success"}}, {"ls_integration": "deepagents", "langgraph_step": 9, "langgraph_node": "tools", "langgraph_triggers": ["__pregel_push"], "langgraph_path": ["__pregel_push", 0, false], "langgraph_checkpoint_ns": "tools:47393f88-5bd5-4e61-053c-533017c5801f"}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "", "response_metadata": {"model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-24be-72d2-8e3e-937b74de6ef4", "tool_calls": [{"name": "edit_file", "args": {}, "id": "call_9aecc91ae22a4b0a9dbf62", "type": "tool_call"}], "tool_call_chunks": [{"name": "edit_file", "args": "{\"file", "id": "call_9aecc91ae22a4b0a9dbf62", "index": 0, "type": "tool_call_chunk"}], "invalid_tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 10, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:ba20c035-2241-9e8b-1ca2-edeeefb54c6f", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:ba20c035-2241-9e8b-1ca2-edeeefb54c6f", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "", "response_metadata": {"model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-24be-72d2-8e3e-937b74de6ef4", "invalid_tool_calls": [{"name": null, "args": "_path\": \"/a", "id": "", "error": null, "type": "invalid_tool_call"}], "tool_call_chunks": [{"name": null, "args": "_path\": \"/a", "id": "", "index": 0, "type": "tool_call_chunk"}], "tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 10, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:ba20c035-2241-9e8b-1ca2-edeeefb54c6f", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:ba20c035-2241-9e8b-1ca2-edeeefb54c6f", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "", "response_metadata": {"model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-24be-72d2-8e3e-937b74de6ef4", "invalid_tool_calls": [{"name": null, "args": ".txt\", \"old", "id": "", "error": null, "type": "invalid_tool_call"}], "tool_call_chunks": [{"name": null, "args": ".txt\", \"old", "id": "", "index": 0, "type": "tool_call_chunk"}], "tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 10, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:ba20c035-2241-9e8b-1ca2-edeeefb54c6f", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:ba20c035-2241-9e8b-1ca2-edeeefb54c6f", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "", "response_metadata": {"model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-24be-72d2-8e3e-937b74de6ef4", "invalid_tool_calls": [{"name": null, "args": "_string\": \"\", \"", "id": "", "error": null, "type": "invalid_tool_call"}], "tool_call_chunks": [{"name": null, "args": "_string\": \"\", \"", "id": "", "index": 0, "type": "tool_call_chunk"}], "tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 10, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:ba20c035-2241-9e8b-1ca2-edeeefb54c6f", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:ba20c035-2241-9e8b-1ca2-edeeefb54c6f", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "", "response_metadata": {"model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-24be-72d2-8e3e-937b74de6ef4", "invalid_tool_calls": [{"name": null, "args": "new_string\": \"", "id": "", "error": null, "type": "invalid_tool_call"}], "tool_call_chunks": [{"name": null, "args": "new_string\": \"", "id": "", "index": 0, "type": "tool_call_chunk"}], "tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 10, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:ba20c035-2241-9e8b-1ca2-edeeefb54c6f", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:ba20c035-2241-9e8b-1ca2-edeeefb54c6f", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "", "response_metadata": {"model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-24be-72d2-8e3e-937b74de6ef4", "invalid_tool_calls": [{"name": null, "args": "这是一些随机", "id": "", "error": null, "type": "invalid_tool_call"}], "tool_call_chunks": [{"name": null, "args": "这是一些随机", "id": "", "index": 0, "type": "tool_call_chunk"}], "tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 10, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:ba20c035-2241-9e8b-1ca2-edeeefb54c6f", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:ba20c035-2241-9e8b-1ca2-edeeefb54c6f", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "", "response_metadata": {"model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-24be-72d2-8e3e-937b74de6ef4", "invalid_tool_calls": [{"name": null, "args": "的内容。\\n这是", "id": "", "error": null, "type": "invalid_tool_call"}], "tool_call_chunks": [{"name": null, "args": "的内容。\\n这是", "id": "", "index": 0, "type": "tool_call_chunk"}], "tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 10, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:ba20c035-2241-9e8b-1ca2-edeeefb54c6f", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:ba20c035-2241-9e8b-1ca2-edeeefb54c6f", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "", "response_metadata": {"model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-24be-72d2-8e3e-937b74de6ef4", "invalid_tool_calls": [{"name": null, "args": "第二行。\\n", "id": "", "error": null, "type": "invalid_tool_call"}], "tool_call_chunks": [{"name": null, "args": "第二行。\\n", "id": "", "index": 0, "type": "tool_call_chunk"}], "tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 10, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:ba20c035-2241-9e8b-1ca2-edeeefb54c6f", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:ba20c035-2241-9e8b-1ca2-edeeefb54c6f", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "", "response_metadata": {"model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-24be-72d2-8e3e-937b74de6ef4", "invalid_tool_calls": [{"name": null, "args": "这是第三行。", "id": "", "error": null, "type": "invalid_tool_call"}], "tool_call_chunks": [{"name": null, "args": "这是第三行。", "id": "", "index": 0, "type": "tool_call_chunk"}], "tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 10, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:ba20c035-2241-9e8b-1ca2-edeeefb54c6f", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:ba20c035-2241-9e8b-1ca2-edeeefb54c6f", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "", "response_metadata": {"model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-24be-72d2-8e3e-937b74de6ef4", "invalid_tool_calls": [{"name": null, "args": "\"}", "id": "", "error": null, "type": "invalid_tool_call"}], "tool_call_chunks": [{"name": null, "args": "\"}", "id": "", "index": 0, "type": "tool_call_chunk"}], "tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 10, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:ba20c035-2241-9e8b-1ca2-edeeefb54c6f", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:ba20c035-2241-9e8b-1ca2-edeeefb54c6f", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "", "response_metadata": {"finish_reason": "tool_calls", "model_name": "qwen2.5-72b-instruct", "model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-24be-72d2-8e3e-937b74de6ef4", "tool_calls": [], "invalid_tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 10, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:ba20c035-2241-9e8b-1ca2-edeeefb54c6f", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:ba20c035-2241-9e8b-1ca2-edeeefb54c6f", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "", "type": "AIMessageChunk", "id": "lc_run--019d23a2-24be-72d2-8e3e-937b74de6ef4", "chunk_position": "last", "tool_calls": [], "invalid_tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 10, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:ba20c035-2241-9e8b-1ca2-edeeefb54c6f", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:ba20c035-2241-9e8b-1ca2-edeeefb54c6f", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "ToolMessage"], "kwargs": {"content": "Successfully replaced 1 instance(s) of the string in '/a.txt'", "type": "tool", "name": "edit_file", "id": "b59ee5a8-fae5-4035-9661-2aba4bb7ce2b", "tool_call_id": "call_9aecc91ae22a4b0a9dbf62", "status": "success"}}, {"ls_integration": "deepagents", "langgraph_step": 12, "langgraph_node": "tools", "langgraph_triggers": ["__pregel_push"], "langgraph_path": ["__pregel_push", 0, false], "langgraph_checkpoint_ns": "tools:45f4cc14-6366-0b10-6ccf-5160ef7079ae"}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "文件", "response_metadata": {"model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-4383-7ec0-ad23-66fa93a50a7c", "tool_calls": [], "invalid_tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 13, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:5ccbe27c-f214-9ee3-7573-30913b6df371", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:5ccbe27c-f214-9ee3-7573-30913b6df371", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]


data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "a.txt", "response_metadata": {"model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-4383-7ec0-ad23-66fa93a50a7c", "tool_calls": [], "invalid_tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 13, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:5ccbe27c-f214-9ee3-7573-30913b6df371", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:5ccbe27c-f214-9ee3-7573-30913b6df371", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": " 已经创建并", "response_metadata": {"model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-4383-7ec0-ad23-66fa93a50a7c", "tool_calls": [], "invalid_tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 13, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:5ccbe27c-f214-9ee3-7573-30913b6df371", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:5ccbe27c-f214-9ee3-7573-30913b6df371", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "写入了以下", "response_metadata": {"model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-4383-7ec0-ad23-66fa93a50a7c", "tool_calls": [], "invalid_tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 13, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:5ccbe27c-f214-9ee3-7573-30913b6df371", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:5ccbe27c-f214-9ee3-7573-30913b6df371", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "内容：\n\n", "response_metadata": {"model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-4383-7ec0-ad23-66fa93a50a7c", "tool_calls": [], "invalid_tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 13, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:5ccbe27c-f214-9ee3-7573-30913b6df371", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:5ccbe27c-f214-9ee3-7573-30913b6df371", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "\n这是一些随机", "response_metadata": {"model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-4383-7ec0-ad23-66fa93a50a7c", "tool_calls": [], "invalid_tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 13, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:5ccbe27c-f214-9ee3-7573-30913b6df371", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:5ccbe27c-f214-9ee3-7573-30913b6df371", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "的内容。\n这是第二", "response_metadata": {"model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-4383-7ec0-ad23-66fa93a50a7c", "tool_calls": [], "invalid_tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 13, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:5ccbe27c-f214-9ee3-7573-30913b6df371", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:5ccbe27c-f214-9ee3-7573-30913b6df371", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "行。\n这是第三", "response_metadata": {"model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-4383-7ec0-ad23-66fa93a50a7c", "tool_calls": [], "invalid_tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 13, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:5ccbe27c-f214-9ee3-7573-30913b6df371", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:5ccbe27c-f214-9ee3-7573-30913b6df371", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "行。\n", "response_metadata": {"finish_reason": "stop", "model_name": "qwen2.5-72b-instruct", "model_provider": "openai"}, "type": "AIMessageChunk", "id": "lc_run--019d23a2-4383-7ec0-ad23-66fa93a50a7c", "tool_calls": [], "invalid_tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 13, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:5ccbe27c-f214-9ee3-7573-30913b6df371", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:5ccbe27c-f214-9ee3-7573-30913b6df371", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [{"lc": 1, "type": "constructor", "id": ["langchain", "schema", "messages", "AIMessageChunk"], "kwargs": {"content": "", "type": "AIMessageChunk", "id": "lc_run--019d23a2-4383-7ec0-ad23-66fa93a50a7c", "chunk_position": "last", "tool_calls": [], "invalid_tool_calls": []}}, {"ls_integration": "langchain_chat_model", "langgraph_step": 13, "langgraph_node": "model", "langgraph_triggers": ["branch:to:model"], "langgraph_path": ["__pregel_pull", "model"], "langgraph_checkpoint_ns": "model:5ccbe27c-f214-9ee3-7573-30913b6df371", "model": "qwen2.5-72b-instruct", "model_name": "qwen2.5-72b-instruct", "stream": false, "temperature": 0.0, "_type": "openai-chat", "checkpoint_ns": "model:5ccbe27c-f214-9ee3-7573-30913b6df371", "ls_provider": "openai", "ls_model_name": "qwen2.5-72b-instruct", "ls_model_type": "chat", "ls_temperature": 0.0}]

data: [DONE]
`
