#!/usr/bin/env python3
"""构建前生成 apps/web/.env：把 GitLab CI/CD Variables 里以 VITE_ 开头的变量写进去。

Vite 把 VITE_ 前缀的环境变量编译进 bundle，所以必须 *构建时* 让它们被 vite 看到。
.env 不入库（只有 .env.example），凭证之类只放在 GitLab CI/CD Variables（Masked）里。
本脚本从当前进程环境读 VITE_*，写到 apps/web/.env，再让 vite/electron-builder 跑构建。

调用：
    python scripts/ci/write-vite-env.py            # 写所有 VITE_* 到 apps/web/.env
    python scripts/ci/write-vite-env.py --append   # 追加而非覆盖（默认是覆盖）

只会把 VITE_ 开头的变量写进去；不会覆盖 .env 里已有的、且不在环境变量里的项（除非
你用 --replace 强制全量覆盖）。
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path


def find_repo_root(start: Path) -> Path:
    for p in [start, *start.parents]:
        if (p / "apps" / "web" / "package.json").exists():
            return p
    raise RuntimeError("找不到仓库根（含 apps/web/package.json）")


def parse_dotenv(text: str) -> dict[str, str]:
    """简单 .env 解析：KEY=VALUE。忽略注释、空行；不处理引号转义。"""
    out: dict[str, str] = {}
    for line in text.splitlines():
        s = line.strip()
        if not s or s.startswith("#") or "=" not in s:
            continue
        k, _, v = s.partition("=")
        out[k.strip()] = v.strip()
    return out


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--append", action="store_true",
                        help="保留 .env 中已有的非 VITE_ 项（默认行为，仅刷新 VITE_*）")
    parser.add_argument("--replace", action="store_true",
                        help="整文件覆盖：丢掉 .env 中所有原有内容，只写当前环境的 VITE_*")
    args = parser.parse_args()

    repo = find_repo_root(Path(__file__).resolve())
    env_file = repo / "apps" / "web" / ".env"

    vite_from_env = {k: v for k, v in os.environ.items() if k.startswith("VITE_")}
    if not vite_from_env:
        print("» 当前环境中未找到 VITE_* 变量；跳过 .env 生成（构建会读 .env.example 默认值）",
              file=sys.stderr)
        return 0

    if args.replace or not env_file.exists():
        existing: dict[str, str] = {}
    else:
        existing = parse_dotenv(env_file.read_text(encoding="utf-8"))

    # VITE_* 用环境变量覆盖；其它保留
    merged = {**existing, **vite_from_env}

    lines = ["# auto-generated by scripts/ci/write-vite-env.py — DO NOT commit",
             "# source: GitLab CI/CD Variables (Masked)"]
    for k in sorted(merged.keys()):
        lines.append(f"{k} = {merged[k]}")
    env_file.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"✓ {env_file.relative_to(repo)} 已写入 {len(vite_from_env)} 个 VITE_* 变量")
    # 不打印 value（凭证可能被截屏/留底）；只列 key
    for k in sorted(vite_from_env):
        print(f"  · {k}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
