#!/usr/bin/env python3
"""构建前生成 apps/web/.env：把 GitLab CI/CD Variables 里以 VITE_ 开头的变量写进去。

Vite 把 VITE_ 前缀的环境变量编译进 bundle，所以必须 *构建时* 让它们被 vite 看到。
.env 不入库（只有 .env.example），凭证之类只放在 GitLab CI/CD Variables（Masked）里。
本脚本从当前进程环境读 VITE_*，写到 apps/web/.env，再让 vite/electron-builder 跑构建。

调用：
    python scripts/ci/write-vite-env.py            # 写所有 VITE_* 到 apps/web/.env
    python scripts/ci/write-vite-env.py --append   # 追加而非覆盖（默认是覆盖）

只会把 VITE_ 开头的变量写进去；不会覆盖 .env 里已有的、且不在环境变量里的项（除非
你用 --replace 强制全量覆盖）。
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path


def find_repo_root(start: Path) -> Path:
    for p in [start, *start.parents]:
        if (p / "apps" / "web" / "package.json").exists():
            return p
    raise RuntimeError("找不到仓库根（含 apps/web/package.json）")


def parse_dotenv(text: str) -> dict[str, str]:
    """简单 .env 解析：KEY=VALUE。忽略注释、空行；不处理引号转义。"""
    out: dict[str, str] = {}
    for line in text.splitlines():
        s = line.strip()
        if not s or s.startswith("#") or "=" not in s:
            continue
        k, _, v = s.partition("=")
        out[k.strip()] = v.strip()
    return out


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--append", action="store_true",
                        help="保留 .env 中已有的非 VITE_ 项（默认行为，仅刷新 VITE_*）")
    parser.add_argument("--replace", action="store_true",
                        help="整文件覆盖：丢掉 .env 中所有原有内容（含 .env.example 兜底），只写当前环境的 VITE_*")
    args = parser.parse_args()

    repo = find_repo_root(Path(__file__).resolve())
    env_file = repo / "apps" / "web" / ".env"
    env_example = repo / "apps" / "web" / ".env.example"

    vite_from_env = {k: v for k, v in os.environ.items() if k.startswith("VITE_")}

    # 关键：vite.config.ts 在 .env 缺失时会从 .env.example 复制兜底（含 BACKEND_URL/PORT
    # 等默认值），我们写 .env 必须先吃掉这份兜底，否则会绕过它、丢掉 BACKEND_URL/PORT，
    # bundle 里出 `undefined:undefined`，客户端登录失败。
    base: dict[str, str] = {}
    if env_example.exists() and not args.replace:
        base = parse_dotenv(env_example.read_text(encoding="utf-8"))

    # 已有的 .env 中非 VITE_* 项也保留（极少见，但稳）
    if env_file.exists() and not args.replace:
        existing = parse_dotenv(env_file.read_text(encoding="utf-8"))
        for k, v in existing.items():
            if not k.startswith("VITE_"):
                base[k] = v

    # GitLab CI/CD Variables（VITE_*）覆盖 example 默认值
    merged = {**base, **vite_from_env}

    if not merged:
        print("» 当前环境/示例文件都没东西可写；跳过 .env 生成", file=sys.stderr)
        return 0

    lines = ["# auto-generated by scripts/ci/write-vite-env.py — DO NOT commit",
             "# base: apps/web/.env.example  ·  overrides: GitLab CI/CD Variables"]
    for k in sorted(merged.keys()):
        lines.append(f"{k} = {merged[k]}")
    env_file.write_text("\n".join(lines) + "\n", encoding="utf-8")

    n_overrides = len(vite_from_env)
    n_total = len(merged)
    print(f"✓ {env_file.relative_to(repo)} 已写入 {n_total} 项"
          f"（其中 {n_overrides} 项来自 GitLab Variables 覆盖）")
    # 不打印 value（凭证可能被截屏/留底）；只列 key
    if vite_from_env:
        print("  覆盖项：")
        for k in sorted(vite_from_env):
            print(f"    · {k}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
