/**
 * IPC channel 常量 — 主进程 handler 与 preload bridge 共用
 */
export const IpcChannels = {
  getBackendStatus: "get-backend-status",
  getBackendPort: "get-backend-port",
  quitApp: "quit-app",
  minimizeWindow: "minimize-window",
  closeWindow: "close-window",
  maximizeWindow: "maximize-window",
  isMaximized: "is-maximized",
  setForceQuit: "set-force-quit",
  getPlatform: "get-platform",
  flashTray: "flash-tray",
  stopFlashTray: "stop-flash-tray",
  sendNotification: "send-notification",
  loginSuccess: "login-success",
  saveAuth: "save-auth",
  clearAuth: "clear-auth",
  getAuthStatus: "get-auth-status",
  hasSavedAuth: "has-saved-auth",
  openRecruitment: "open-recruitment",
  closeRecruitment: "close-recruitment",
  hireSuccess: "hire-success",
  openRegister: "open-register",
  closeRegister: "close-register",
  registerSuccess: "register-success",
  resizeRegisterWindow: "resize-register-window",
  openSettings: "open-settings",
  closeSettings: "close-settings",
  setAutoLaunch: "set-auto-launch",
  getAutoLaunch: "get-auto-launch",
  setNotifications: "set-notifications",
  getNotifications: "get-notifications",
  setAutoUpdate: "set-auto-update",
  getAutoUpdate: "get-auto-update",
  getPetSettings: "get-pet-settings",
  setPetSettings: "set-pet-settings",
  petGetSelected: "pet:get-selected",
  petSelect: "pet:select",
  petListPetdex: "pet:list-petdex",
  petGetPetdexMeta: "pet:get-petdex-meta",
  petShow: "pet:show",
  petHide: "pet:hide",
  petSetPosition: "pet:set-position",
  petGetPosition: "pet:get-position",
  getOnboardingCompleted: "get-onboarding-completed",
  setOnboardingCompleted: "set-onboarding-completed",
  getModelSettings: "get-model-settings",
  setModelSettings: "set-model-settings",
  getEndpoint: "get-endpoint",
  setEndpoint: "set-endpoint",
  resetApp: "reset-app",
  checkUpdate: "check-update",
  startDownload: "start-download",
  quitAndInstall: "quit-and-install",
} as const

export type IpcChannel = (typeof IpcChannels)[keyof typeof IpcChannels]
